run:
  timeout: 5m
  issues-exit-code: 1
  modules-download-mode: readonly

linters-settings:
  goimports:
    local-prefixes: github.com/cheelim1/argocd-actions
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: false
  funlen:
    lines: 80

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goerr113
        - gocyclo
        - errcheck
        - gosec
        - dupl
        - funlen
        - testpackage
        - ifshort
        - paralleltest

linters:
  disable-all: false
  enable:
    - govet
    - golint
    - staticcheck
    - gofmt
    - goimports
    - misspell
    - nolintlint
    - funlen
  disable:
    - exhaustivestruct
    - wrapcheck
    - gomoddirectives
    - errorlint  # Temporarily disable errorlint
    - errcheck  # Temporarily disable errcheck
