name: "ArgoCD Sync Actions +"
description: "Sync ArgoCD apps based on app name or labels"
author: "cheelim1"
branding:
  icon: refresh-cw
  color: 'gray-dark'
inputs:
  address:
    description: "ArgoCD server address"
    required: true
  token:
    description: "ArgoCD token"
    required: true
  action:
    description: "Action name"
    required: true
  application: #appName
    description: "Application name to sync"
    required: false
  image:
    description: "Image tag for the binary"
    required: false
    default: "latest"
  labels:
    description: "Labels to sync the ArgoCD app"
    required: false    
  sync_retries:
    description: "Number of retry attempts if sync fails"
    required: false
    default: "5"
  sync_interval:
    description: "Duration to wait between retries (e.g. '10s', '1m')"
    required: false
    default: "10s"

runs:
  using: "composite"
  steps:
    - name: Run argocd-actions CLI from the image for GH image registry
      run: |
        docker run --rm -i ghcr.io/cheelim1/argocd-actions:${{ inputs.image }} \
          ${{ inputs.action }} \
          --application=${{ inputs.application }} \
          --labels=${{ inputs.labels }} \
          --token=${{ inputs.token }} \
          --address=${{ inputs.address }} \
          --sync-retries=${{ inputs.sync_retries }} \
          --sync-interval=${{ inputs.sync_interval }} \
          --logLevel=debug
      shell: sh
