name: "ArgoCD Sync Actions +"
description: "Sync ArgoCD apps based on app name or labels"
author: "cheelim1"
branding:
  icon: terminal
  color: 'gray-dark'
inputs:
  address:
    description: "ArgoCD server address"
    required: true
  token:
    description: "ArgoCD token"
    required: true
  action:
    description: "Action name"
    required: true
  application: #appName
    description: "Application name to sync"
    required: false
  image:
    description: "Image tag for the binary"
    required: false
    default: "latest"
  labels:
    description: 'Labels to sync the ArgoCD app'
    required: false

runs:
  using: "composite"
  steps:
    - name: Run argocd-actions CLI from the image for GH image registry
      run: |
        docker run --rm -i ghcr.io/cheelim1/argocd-actions:${{ inputs.image }} \
          ${{ inputs.action }} \
          --application=${{ inputs.appName }} \
          --token=${{ inputs.token }} \
          --address=${{ inputs.address }} \
          --logLevel=debug
      shell: sh
